# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the Polygon Area;
#' @param X required
#' @param Y required
#' @return Area
#' @export
polygonArea <- function(X, Y) {
    .Call('_rSHUD_polygonArea', PACKAGE = 'rSHUD', X, Y)
}

#' Identify whether every row of x is same as m;
#' @param x Row vector
#' @param m Matrix
#' @return TRUE/FALSE of matching
#' @useDynLib rSHUD
#' @export
rowMatch <- function(x, m) {
    .Call('_rSHUD_rowMatch', PACKAGE = 'rSHUD', x, m)
}

#' Determine the topological relation among triangles. 
#' @param tri triangle defination, m x 3
#' @return topological relation of triangles. m x 4; cols = c(ID, Nabor1, Nabor2, Nabor3)
#' @export
triTopology <- function(tri) {
    .Call('_rSHUD_triTopology', PACKAGE = 'rSHUD', tri)
}

